### PR TITLE
Auto format workflow

### PR DESCRIPTION
**Pull request by Raptorly1**
#### Summary

On Push, changes in each file will be reviewed and replaced with code that follows the .clang-format file in the repo. I currently only wrote it to use the first .clang-format file it finds in the repo. I can change it.
#### Motivation

Requested and not every contributor knows clang-format too well
#### Test Plan

tested in other repos
#### Additional Notes

heavily optimized to take max 20s probably for the entire codebase reformat. You may make any change to the .clang-format file and the script will reformat everything

## Download the template for this pull request: 

> [!NOTE]  
> This is auto generated from [`Add Template to Pull Request`](https://github.com/LemLib/LemLib/actions/runs/8826012023)
- via manual download: [LemLib@0.5.0-rc.7+7540d0.zip](https://nightly.link/LemLib/LemLib/actions/artifacts/1445563315.zip)
- via PROS Integrated Terminal: 
 ```
curl -o LemLib@0.5.0-rc.7+7540d0.zip https://nightly.link/LemLib/LemLib/actions/artifacts/1445563315.zip;
pros c fetch LemLib@0.5.0-rc.7+7540d0.zip;
pros c apply LemLib@0.5.0-rc.7+7540d0;
rm LemLib@0.5.0-rc.7+7540d0.zip;
```

### CODE REVIEW

**Comment by ABUCKY0** [comment]
This should probably operate exclusively on LemLib's code, so it won't cause any issues in the future with PROS and templating.

**Comment by Raptorly1** [comment]
Good idea @ABUCKY0. I did that in commit number 13 https://github.com/LemLib/LemLib/pull/178/commits/e257b5845a94c460b7ca941f11afeb7ca48ff22c. BTW, any ideas for the commit history issue thing? I'm thinking maybe run the workflow on merge or weekly or something of that sort.

**Comment by Raptorly1** [comment]
https://discord.com/channels/1094397185141002340/1094409043331776552/1232788652254433462

**Comment by liam-teale** [comment]
this still being worked on?

**Comment by liam-teale** [comment]
implemented by #241

**Pull request closed without merging**
