### PR TITLE
Created a Custom moveVelocity System and Added Double Overload for lemlib::avg()

### PR DESCRIPTION
**Pull request by ItzSt0rmz**
#### Summary
(a) Created a custom moveVelocity function for motor groups to replace the flawed VEX move_velocity. It uses a TBH controller and the move voltage function inside a task, with a different task for each motor group.

(b) Added a double overload for lemlib;:avg()

#### Motivation
(a) Sets up #4 to be solved when unit system is implemented, and directly solves #102

(b) Makes working with motor groups easier

#### Test Plan
(a) Test on robot when accessed

(b) Doesn't really need it

#### Additional Notes
- The tasking could go very wrong
- Values like kI and take-back value probably need tuned
- PIDs set up but not implemented

## Download the template for this pull request: 

> [!NOTE]  
> This is auto generated from [`Add Template to Pull Request`](https://github.com/LemLib/LemLib/actions/runs/6986414462)
- via manual download: [LemLib@0.5.0-rc1+b6d097.zip](https://nightly.link/LemLib/LemLib/actions/artifacts/1072356048.zip)
- via PROS Integrated Terminal: 
 ```
curl -o LemLib@0.5.0-rc1+b6d097.zip https://nightly.link/LemLib/LemLib/actions/artifacts/1072356048.zip;
pros c fetch LemLib@0.5.0-rc1+b6d097.zip;
pros c apply LemLib@0.5.0-rc1+b6d097;
rm LemLib@0.5.0-rc1+b6d097.zip;
```

### CODE REVIEW

**Comment by liam-teale** [comment]
Can you merge this into the refactor branch instead? That's where development is focused atm

**Comment by ItzSt0rmz** [comment]
Shoot, I might need to change some stuff to work with the refactor then.

**Comment by liam-teale** [comment]
You have some merge conflicts that need to be solved b4 this can be merged

**Comment by ItzSt0rmz** [comment]
Yea I'm going to work on it today, it needs to be reformatted for the refactor.

**Comment by ItzSt0rmz** [comment]
TO-DO:

- abstract settle util
- abstract controller (VAP)
- gain schedular (steal #110 implementation somehow)

**Pull request closed without merging**
