### PR TITLE
[FEATURE] Implementing Modular Individual Motor PID

### PR DESCRIPTION
**Pull request by LycoKodo**
#### **Summary**  
While lemlib provides modular design with the PID class, and PROS have the .move_relative() method, there still lacks a modular design for implementing PID into individual motors. 

This PR addresses this issue by introducing a new `SmartMotor` class that provides a PID control interface for motors using different types of position sensors. The class provides support for inputs from:  

1. **ADI Encoders (3-wire encoders)**  
2. **V5 Rotation Sensors**  
3. **Integrated Motor Encoders (IME)**  

and also supports PID controlled motor groups.

---

#### **Motivation**  
As a member of Team 1831E competing in the "High Stakes" season, I encountered significant challenges while programming macros for key mechanisms—specifically the "lady brown" and "fish mech" subsystems. The lack of robust support for individual motor PID control in both PROS and the current LemLib made the codebase repetitive, harder to manage, and less adaptable.

To address this, I developed the SmartMotor class to provide a simplified and modular interface for PID control. This design enables teams—especially newer teams—to seamlessly implement PID control not only for drivetrains but also for individual subsystems.

This level of control is especially critical in the High Stakes season, where precise mechanism performance is often the deciding factor, and will likely remain essential in future seasons.

---

#### **Test Plan**  
✅ Compiles
✅ Similar algorithm is competition tested on our robot

Please let me know if theres any more stuff yall would like to be testd. 

---

#### **Additional Notes**  
- Debug logging ( through`printf`) was included to monitor PID behavior during testing. These can be removed or replaced with a logger interface for production.  
- The `movePID` method includes a small delay (10 ms) to ensure stable control loop timing.

## Download the template for this pull request: 

> [!NOTE]  
> This is auto generated from [`Add Template to Pull Request`](https://github.com/LemLib/LemLib/actions/runs/12370059003)
- via manual download: [LemLib@0.5.5+d79dff.zip](https://nightly.link/LemLib/LemLib/actions/artifacts/2330864626.zip)
- via PROS Integrated Terminal: 
 ```
curl -o LemLib@0.5.5+d79dff.zip https://nightly.link/LemLib/LemLib/actions/artifacts/2330864626.zip;
pros c fetch LemLib@0.5.5+d79dff.zip;
pros c apply LemLib@0.5.5+d79dff;
rm LemLib@0.5.5+d79dff.zip;
```

### CODE REVIEW

**Comment by Ynthra** [comment]
I think this should be in Lemlib/hardware if anything rather than this repo

**Comment by LycoKodo** [comment]
Apologies, this is my first PR to lemlib, but is Lemlib/hardware related to **lemlib being rewritten for v0.6.0**?

So would you like for me to start a PR for that repo?

Cheers 🍻

**Comment by liam-teale** [comment]
Hello @LycoKodo, sorry for the delayed response. Life has decided to mess with me this last little while.

Answering your questions:

[LemLib/hardware](https://github.com/LemLib/hardware) is a template providing unitized hardware abstractions for sensors and motors. It would be great if you could open this as a feature request in there, so we can discuss this idea and whether it would be a good fit or not. I think it's a good idea, but I want to see what other community members think as well, since they are usually much smarter than I am.

**Comment by liam-teale** [comment]
closing, as this should be done in LemLib/hardwarez

**Pull request closed without merging**
