### PR TITLE
ChassisBuilder and Chassis Classes Refactor

### LINKED ISSUE #25: [FEATURE] Holonomic Drivetrain Support
**Requested Feature**
Holonomic drivetrain support

**Motivation**
Currently, only differential drivetrains are supported. This limits who can use LemLib. These drivetrains are still very popular, and it makes sense to support them.

**Implementation**
This can be implemented by creating an abstract `Chassis` class, and then having classes such as `Differential` or `Holonomic`

### PR DESCRIPTION
**Pull request by Rocky14683**
#### Summary
ChassisBuilder allows users to construct different types of drivetrains easier. 

#### Motivation
Added support for missing drivetrains

#### Todo

- [x] Swerve Drive
- [x] Format

#### Test Plan

- [ ] ...

### CODE REVIEW

**Comment by Exortions** [comment]
WOOOOO ROCKY OP

**Comment by liam-teale** [comment]
Is this ready for review?

**Comment by Rocky14683** [comment]
> Is this ready for review?

YES!!!

**Comment by Exortions** [comment]
might want to add PTO to this tho

**Comment by liam-teale** [comment]
Unfortunately I'm gonna have to close this as its no longer planned. Terribly sorry

**Pull request closed without merging**
